"use client";
import { useEffect, useState } from 'react';
import { getAllProductsAdmin, saveProductAdmin, getCategories } from "@/lib/api";
import ProductTableClient from "./ProductTableClient";

export default function AdminProductsPage() {
  const [products, setProducts] = useState<any[]>([]);
  const [categories, setCategories] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({
    id: '', name: '', price: '', cost_price: '', promo_price: '', stock: '', category: 'Al-Qur\'an',
    weight: '1000', description: '', image_url: '', status: 'ACTIVE'
  });

  async function loadData() {
    setLoading(true);
    try {
      const [prodData, catData] = await Promise.all([
        getAllProductsAdmin(),
        getCategories()
      ]);
      setProducts(prodData || []);
      setCategories(catData || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadData();
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    try {
      // id will be generated by backend if left empty
      const payload = {
        product_id: form.id,
        name: form.name,
        price: form.price,
        cost_price: form.cost_price,
        promo_price: form.promo_price,
        stock: form.stock,
        category_id: form.category,
        weight: form.weight,
        description: form.description,
        image: form.image_url,
        is_active: form.status === 'ACTIVE'
      };

      const res = await saveProductAdmin(payload);
      if (res.success) {
        setShowForm(false);
        setForm({ id: '', name: '', price: '', cost_price: '', promo_price: '', stock: '', category: categories.length > 0 ? categories[0].category_id : '', weight: '1000', description: '', image_url: '', status: 'ACTIVE' });
        loadData();
      } else {
        alert("Gagal menyimpan produk: " + res.message);
      }
    } catch (err) {
      alert("Terjadi kesalahan jaringan");
    } finally {
      setSaving(false);
    }
  }

  return (
    <div>
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
        <div>
          <h1 className="text-3xl font-black text-foreground">Katalog Produk</h1>
          <p className="text-foreground/60 mt-1">Kelola inventaris dan stok barang dagangan.</p>
          {products.filter((p: any) => Number(p.stock) <= 5).length > 0 && (
            <p className="text-xs text-red-500 font-semibold mt-1 flex items-center gap-1">
              ⚠️ {products.filter((p: any) => Number(p.stock) <= 5).length} produk stok menipis (≤ 5)
            </p>
          )}
        </div>
        <div className="flex gap-2">
          <button onClick={() => setShowForm(!showForm)} className="bg-white border text-foreground px-4 py-2 rounded-xl font-bold hover:bg-gray-50 shadow-sm">
            {showForm ? 'Batal' : '+ Tambah Produk'}
          </button>
          <button onClick={loadData} className="bg-primary text-white px-4 py-2 rounded-xl font-bold hover:bg-primary-hover shadow-sm">
            Muat Ulang
          </button>
        </div>
      </div>
      
      {showForm && (
        <div className="bg-white p-6 rounded-2xl border mb-8 shadow-sm">
          <h3 className="font-bold text-lg mb-4">Tambah / Edit Produk</h3>
          <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="md:col-span-2">
              <label className="block text-sm font-medium mb-1">Nama Produk</label>
              <input required value={form.name} onChange={e => setForm({...form, name: e.target.value})} className="w-full px-4 py-2 border rounded-xl" placeholder="Contoh: Al-Qur'an Tajwid" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Harga Pokok / HPP (Rp)</label>
              <input type="number" value={form.cost_price} onChange={e => setForm({...form, cost_price: e.target.value})} className="w-full px-4 py-2 border rounded-xl" placeholder="80000" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Harga Jual (Rp)</label>
              <input required type="number" value={form.price} onChange={e => setForm({...form, price: e.target.value})} className="w-full px-4 py-2 border rounded-xl" placeholder="100000" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Harga Promo (Rp) <span className="text-gray-400 font-normal">- opsional</span></label>
              <input type="number" value={form.promo_price} onChange={e => setForm({...form, promo_price: e.target.value})} className="w-full px-4 py-2 border rounded-xl" placeholder="Kosongkan jika tidak ada promo" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Stok</label>
              <input required type="number" value={form.stock} onChange={e => setForm({...form, stock: e.target.value})} className="w-full px-4 py-2 border rounded-xl" placeholder="50" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Kategori</label>
              <select value={form.category} onChange={e => setForm({...form, category: e.target.value})} className="w-full px-4 py-2 border rounded-xl bg-white">
                {categories.map((c: any) => (
                  <option key={c.category_id} value={c.category_id}>{c.name}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Berat (gram)</label>
              <input type="number" value={form.weight} onChange={e => setForm({...form, weight: e.target.value})} className="w-full px-4 py-2 border rounded-xl" placeholder="1000" />
            </div>
            <div className="md:col-span-2">
              <label className="block text-sm font-medium mb-1">URL Gambar</label>
              <input required value={form.image_url} onChange={e => setForm({...form, image_url: e.target.value})} className="w-full px-4 py-2 border rounded-xl" placeholder="https://..." />
            </div>
            <div className="md:col-span-2">
              <label className="block text-sm font-medium mb-1">Deskripsi Singkat</label>
              <textarea value={form.description} onChange={e => setForm({...form, description: e.target.value})} className="w-full px-4 py-2 border rounded-xl" rows={3}></textarea>
            </div>
            <div className="md:col-span-2 flex justify-end mt-2">
              <button disabled={saving} type="submit" className="bg-gray-800 text-white px-6 py-2 rounded-xl font-bold">
                {saving ? 'Menyimpan...' : 'Simpan Produk'}
              </button>
            </div>
          </form>
        </div>
      )}

      <div className="bg-white border border-border rounded-2xl overflow-hidden shadow-sm p-1">
        <ProductTableClient 
          initialProducts={products} 
          loading={loading} 
          onEdit={(item) => {
            setForm({ 
              id: item.id, 
              name: item.name, 
              price: item.price,
              cost_price: item.cost_price || '',
              promo_price: item.promo_price || '',
              stock: item.stock, 
              category: item.category_id || item.category, 
              weight: item.weight || '1000', 
              description: item.description || '', 
              image_url: item.image_url || item.image || '', 
              status: item.status || 'ACTIVE' 
            });
            setShowForm(true);
            window.scrollTo({ top: 0, behavior: 'smooth' });
          }}
        />
      </div>
    </div>
  );
}
